name: CI Workflow

on:
  push:
    branches: 
      - dev 
      - master
  pull_request:
    branches:
      - dev
      - master
      
jobs:
  perform_tests:
    name: Perform Tests and report code coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies and perform the tests
        env:
          TEST_ACCOUNT_USERNAME: ${{ secrets.MINECRAFT_TEST_ACCOUNT_MAIL }}
          TEST_ACCOUNT_PASSWORD: ${{ secrets.MINECRAFT_TEST_ACCOUNT_PASS }}
        run: |
          npm ci
          npm run test:unit
          npm run build:all
      - name: Upload coverage reports to coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
