name: master branch CI task

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node JS
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        env:
          TEST_ACCOUNT_USERNAME: ${{ secrets.MINECRAFT_TEST_ACCOUNT_MAIL }}
          TEST_ACCOUNT_PASSWORD: ${{ secrets.MINECRAFT_TEST_ACCOUNT_PASS }}
      - run: npm ci
      - run: npm run test:unit
      - run: npm run build:all